env:
  browser: true
  es6: true
  jquery: true
extends: 'eslint:recommended'
globals:
  Site: true
parserOptions:
  ecmaVersion: 2016
  sourceType: 'module'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - warn
    - unix
  max-len:
    - error
    - code: 80
    - ignoreTrailingComments: true
    - ignoreUrls: true
  no-console:
    - warn
    - allow:
      - group
      - groupCollapsed
      - groupEnd
      - error
      - warn
  quotes:
    - error
    - single
  semi:
    - error
    - always
